[ DB ]
User = "postgres"
PswdEnvVar = "DB_PSWD"
Name = "provlib_tests"
Host = "localhost"
Port = 5432

[ Logging ]
Verbosity = 3
SaveTo = "../../bs/logs"
Name = "runningTest"

[ Global ]
BatchSize = 5

[ BarPathCalc ]
MinNumSamples = 5

# To simplify testing
# [ PhysicsJobQueue ]
# QueueLen = 1
# MaxNumWorkers = 1
# MaxJobsPerPoll = 1
